# Generated by Django 4.2.6 on 2023-11-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='STUDENT',
        ),
    ]
