# Generated by Django 4.2.6 on 2023-11-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='employee',
        ),
    ]
