# Generated by Django 4.2.6 on 2023-11-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_signup_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='peoplesign',
        ),
    ]
