# Generated by Django 4.2.6 on 2023-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_alter_signup_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='peoplesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('number', models.BigIntegerField()),
            ],
            options={
                'db_table': 'peoplesign',
            },
        ),
        migrations.RenameModel(
            old_name='student',
            new_name='emp',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
